WITH RECURSIVE THIRD(ID, PARENT_ID, N) AS (
    SELECT ID, PARENT_ID, 1 AS N
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT R.ID, R.PARENT_ID, THIRD.N+1 AS N
    FROM ECOLI_DATA AS R
    INNER JOIN THIRD ON R.PARENT_ID = THIRD.ID
)
SELECT ID
FROM THIRD 
WHERE N = 3
