-- SELECT 1은 해당 조건이 만족되는지 여부를 확인
-- EXISTS 하려면 그 뒤에 쿼리값이 와야 함.
WITH UP AS (
    SELECT DISTINCT(A.ITEM_ID) AS ID
    FROM ITEM_TREE A
    JOIN ITEM_TREE B
    ON A.ITEM_ID = B.PARENT_ITEM_ID
)

SELECT D.ITEM_ID, D.ITEM_NAME, D.RARITY
FROM ITEM_INFO AS D
WHERE NOT EXISTS (
    SELECT 1
    FROM UP AS C
    WHERE D.ITEM_ID = C.ID  
)
ORDER BY D.ITEM_ID DESC