-- 코드를 입력하세요 
-- Group by로 code에 맞춰서 SUM.
-- Join on으로 ID에 맞춰서 count.
SELECT A.PRODUCT_CODE, SUM(PRICE * SALES_AMOUNT) AS SALES  
FROM PRODUCT A
JOIN OFFLINE_SALE B ON A.PRODUCT_ID=B.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE;