SELECT A.ID, IF(PER <= 0.25, 'CRITICAL', IF(PER <= 0.5,'HIGH', IF(PER <= 0.75,'MEDIUM', 'LOW'))) AS COLONY_NAME
FROM ECOLI_DATA AS A 
JOIN 
(SELECT ID, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS PER FROM ECOLI_DATA) AS B ON A.ID = B.ID
ORDER BY A.ID



