-- 코드를 입력하세요
WITH MAX_PRICE AS (
    SELECT MAX(PRICE) AS M_PRICE
    FROM FOOD_PRODUCT
)

SELECT PRODUCT_ID,	PRODUCT_NAME,	PRODUCT_CD,	CATEGORY,	PRICE
FROM FOOD_PRODUCT AS A, MAX_PRICE AS B
WHERE A.PRICE = B.M_PRICE