-- 코드를 작성해주세요
SELECT B.ITEM_ID, A.ITEM_NAME, A.RARITY
FROM ITEM_TREE AS B
INNER JOIN ITEM_INFO AS A
ON B.ITEM_ID = A.ITEM_ID
WHERE PARENT_ITEM_ID IN
(SELECT ITEM_ID
FROM ITEM_INFO
WHERE RARITY = 'RARE')
ORDER BY B.ITEM_ID DESC
