-- 코드를 작성해주세요
WITH MAX_SIZE AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS BIG
    FROM ECOLI_DATA
    GROUP BY YEAR   
)

SELECT B.YEAR, (B.BIG - A.SIZE_OF_COLONY) AS YEAR_DEV, A.ID
FROM MAX_SIZE AS B INNER JOIN ECOLI_DATA AS A 
WHERE YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR, YEAR_DEV