-- 코드를 작성해주세요
WITH WINNER AS (
SELECT A.EMP_NO, SUM(SCORE) AS SCORE
FROM HR_GRADE AS A
GROUP BY A.EMP_NO
ORDER BY SCORE DESC
LIMIT 1
)

SELECT W.SCORE, W.EMP_NO, H.EMP_NAME, H.POSITION, H.EMAIL
FROM WINNER AS W LEFT JOIN HR_EMPLOYEES AS H 
ON W.EMP_NO = H.EMP_NO


